# base image
FROM python:3.8.5-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python3-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
WORKDIR /app

# add and install requirements
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint-prod.sh
COPY ./entrypoint-prod.sh /app/entrypoint-prod.sh
RUN chmod +x /app/entrypoint-prod.sh

# add app
COPY . /app

# run server
CMD ["/app/entrypoint-prod.sh"]