version: '3.7'

services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile-Flask
    volumes:
      - '.:/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/example_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/example_test
    depends_on: 
      - db

  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile-Postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres