name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.yml up --build -d
      - name: Lint
        continue-on-error: true 
        run: docker-compose exec -T flask flake8 project
      - name: Tests
        continue-on-error: true 
        run: docker-compose exec -T flask python manage.py test